// Pure parser for HMA's own GST Bills "Download Report" export (see
// BASE_HEADERS / handleExport in GstBillsView.jsx). Input is the raw rows
// array from XLSX.utils.sheet_to_json(ws, { header: 1, defval: '' }).
//
// The export has an exact, known header row (it's generated by this same
// app), so headers are matched exactly rather than by fuzzy prefix.
//
// Multi-rate bills are rendered in the export as: a group-band row (blank
// GST No / Invoice Number), one row per GST rate (same GST No + Invoice
// Number, repeated), then a bold "BILL TOTAL" row carrying the summed
// total value (also same GST No + Invoice Number). Re-parsing that would
// otherwise count one invoice 2-3 times. We dedupe by (GST No, Invoice
// Number): rows are upserted into a map in sheet order, so the BILL TOTAL
// row — which appears last for its invoice — naturally wins and supplies
// the summed value; single-rate bills are unaffected since they have only
// one row per invoice.

const normalizeHeader = (h) =>
  String(h ?? '')
    .toLowerCase()
    .replace(/[^a-z0-9]/g, '')

const FIELD_BY_HEADER = {
  gstno: 'gstNo',
  invoicenumber: 'invoiceNumber',
  partyname: 'partyName',
  department: 'department',
  vertical: 'vertical',
  invoicedate: 'invoiceDate',
  totalvalueincltax: 'totalValue',
}

const toNumberOrNull = (v) => {
  if (v == null) return null
  const s = String(v).trim()
  if (s === '') return null
  const n = Number(s)
  return Number.isFinite(n) ? n : null
}

const text = (v) => String(v ?? '').trim()

export const parseOwnGstReport = (rows) => {
  const headerIdx = rows.findIndex((row) => {
    if (!Array.isArray(row)) return false
    const norms = row.map(normalizeHeader)
    return norms.includes('gstno') && norms.includes('invoicenumber')
  })
  if (headerIdx === -1) return { error: 'HEADER_NOT_FOUND', entries: [] }

  const cols = {} // field name → column index
  rows[headerIdx].forEach((h, i) => {
    const field = FIELD_BY_HEADER[normalizeHeader(h)]
    if (field && cols[field] === undefined) cols[field] = i
  })

  const byKey = new Map() // "GSTNO|INVOICE" → entry, later rows overwrite earlier ones
  for (let i = headerIdx + 1; i < rows.length; i++) {
    const row = rows[i]
    if (!Array.isArray(row)) continue

    const gstNo = text(row[cols.gstNo]).toUpperCase()
    const invoiceNumber = text(row[cols.invoiceNumber])
    if (!gstNo || !invoiceNumber) continue // title / blank / group-band row

    const key = `${gstNo}|${invoiceNumber.toUpperCase()}`
    byKey.set(key, {
      gstNo,
      invoiceNumber,
      partyName: text(row[cols.partyName]),
      department: text(row[cols.department]),
      vertical: text(row[cols.vertical]),
      invoiceDate: text(row[cols.invoiceDate]),
      totalValue: toNumberOrNull(row[cols.totalValue]) ?? 0,
    })
  }
  return { error: null, entries: [...byKey.values()] }
}
