/**
 * sdpProjectsData.js
 * ─────────────────────────────────────────────────────────────────────────────
 * Source: /docs/Projects sdp .csv  (CSR - SDP Projects 2026-2027)
 *
 * All 17 projects parsed from the CSV with their full details:
 * installments, phases, officers, beneficiaries, financials, location.
 *
 * Column mapping from CSV row 3:
 *   0  Sl No            1  Project Number       2  Project Name
 *   3  Funding Agency   4  Implementation Partner  5  Project Location
 *   6  Type of Project  7  Status               8  Project Components
 *   9  Duration        10  Start Date           11  End Date
 *  12  Total Beneficiaries  13 Beneficiaries completed  14 Project Value
 *  15  Fund Installments   16  Fund Status       17  Project Milestones
 *  18  UC target date  19  UC Status            20  Total Expense accounted
 *  21  Total Committed Expense  22  Fund Balance  23  Project Officer
 *  24  Field Team      25  Project Phase        26  Project Phase status
 *  27  Current activities  28  Pending activities  29  Pending Target Date
 *  30  Risk/Challenges  31  Weekly Report       32  Remarks
 */

/**
 * Coordinate lookup for Indian cities/districts present in the CSV.
 */
export const CITY_COORDS = {
  yelahanka: { lat: 13.1007, lng: 77.5963 },
  bangalore: { lat: 12.9716, lng: 77.5946 },
  bengaluru: { lat: 12.9716, lng: 77.5946 },
  giridh: { lat: 24.185, lng: 86.3037 },
  jharkhand: { lat: 23.6102, lng: 85.2799 },
  thiruvananthapuram: { lat: 8.5241, lng: 76.9366 },
  trivandrum: { lat: 8.5241, lng: 76.9366 },
  wayanad: { lat: 11.6854, lng: 76.132 },
  simdega: { lat: 22.6166, lng: 84.5124 },
  nilgiris: { lat: 11.4064, lng: 76.6932 },
  ooty: { lat: 11.4064, lng: 76.6932 },
  maharashtra: { lat: 19.7515, lng: 75.7139 },
  beed: { lat: 18.9876, lng: 75.7597 },
  konni: { lat: 9.0055, lng: 76.9421 },
  pathanamthitta: { lat: 9.2648, lng: 76.787 },
  kadapa: { lat: 14.4673, lng: 78.8242 },
  'andhra pradesh': { lat: 15.9129, lng: 79.74 },
  kanpur: { lat: 26.4499, lng: 80.3319 },
  'uttar pradesh': { lat: 26.8467, lng: 80.9462 },
  faridabad: { lat: 28.4089, lng: 77.3178 },
  haryana: { lat: 29.0588, lng: 76.0856 },
  bihar: { lat: 25.0961, lng: 85.3131 },
  kochi: { lat: 9.9312, lng: 76.2673 },
  kerala: { lat: 10.8505, lng: 76.2711 },
  lucknow: { lat: 26.8467, lng: 80.9462 },
  bhubaneswar: { lat: 20.2961, lng: 85.8245 },
  kolkata: { lat: 22.5726, lng: 88.3639 },
  delhi: { lat: 28.6139, lng: 77.209 },
  mumbai: { lat: 19.076, lng: 72.8777 },
  hyderabad: { lat: 17.385, lng: 78.4867 },
  ranchi: { lat: 23.6102, lng: 85.2799 },
  chennai: { lat: 13.0827, lng: 80.2707 },
}

/** Resolve a text location string -> { lat, lng, label } */
export const resolveCoords = (locationText) => {
  if (!locationText) return { lat: 20.5937, lng: 78.9629, label: 'India' }
  const lower = locationText.toLowerCase()
  for (const [key, coords] of Object.entries(CITY_COORDS)) {
    if (lower.includes(key)) return { ...coords, label: locationText }
  }
  return { lat: 20.5937, lng: 78.9629, label: locationText }
}

// ─────────────────────────────────────────────────────────────────────────────
// ALL PROJECTS — parsed from CSV
// ─────────────────────────────────────────────────────────────────────────────

export const SDP_PROJECTS = [
  {
    id: 'sdp_01',
    sl_no: 1,
    project_number: '',
    name: 'Powergrid - Awareness Creation & Distribution of Menstrual Cups at Singnayakahalli Panchayat & Govt PU College Yelahanka',
    funding_agency: 'Powergrid',
    implementing_partner: 'HMA',
    location: 'Yelahanka',
    type: 'M Cup Project - CSR',
    status: 'Completed',
    components: 'Menstrual Cup',
    duration: '1 Year',
    start_date: '15/04/2025',
    end_date: '14/04/2026',
    beneficiaries_target: 5000,
    beneficiaries_completed: 5000,
    value: 1850100,
    expense_accounted: 1850100,
    committed_expense: 0,
    fund_balance: 0,
    project_officer: 'Dr. Arjuna V Nath',
    field_team: 'Ms. Navya, Ms. Chaithra',
    remarks: 'Interim Report Submitted on 25.02.2026',
    installments: [
      {
        label: '1st Installment (50%)',
        amount: 925050,
        status: 'Received',
        milestone: 'Upon Signing of MoU (50% of actual cost)',
        uc_date: '',
        uc_status: '',
      },
      {
        label: '2nd Installment',
        amount: 740040,
        status: 'Received',
        milestone: 'Upon Completion of 40% of work and submission of UC for 1st installment',
        uc_date: '15.02.2026',
        uc_status: '25.02.2026',
      },
      {
        label: '3rd Installment',
        amount: 185010,
        status: 'Received',
        milestone: 'Upon Completion of 100% of work and submission of 100% UC',
        uc_date: '13.04.2026',
        uc_status: '',
      },
    ],
    phases: [
      {
        phase: 'Design & Initiation Phase',
        status: 'Completed',
        current: 'Awareness Session & Refreshment Session',
        pending: 'Final UC not submitted to funding agency',
      },
      { phase: 'Implementation Phase', status: 'Completed', current: '', pending: '' },
      { phase: 'Monitoring & Evaluation Phase', status: 'Completed', current: '', pending: '' },
    ],
  },
  {
    id: 'sdp_02',
    sl_no: 2,
    project_number: '',
    name: 'IOCL ERPL Kolkata - Sanitary Napkin Vending Machine & Menstrual Hygiene Awareness',
    funding_agency: 'IOCL ERPL Kolkata',
    implementing_partner: 'H&ND',
    location: 'Giridh, Jharkhand',
    type: 'Consultancy Project - CSR',
    status: 'Ongoing',
    components:
      '20 Sanitary Napkin Vending Machines, Incinerators, 108000 packs Happy Days-3, 20 Awareness Sessions',
    duration: '2 Months',
    start_date: '10.03.2026',
    end_date: '30.04.2026',
    beneficiaries_target: 0,
    beneficiaries_completed: 0,
    value: 2519529,
    expense_accounted: 0,
    committed_expense: 0,
    fund_balance: 0,
    project_officer: 'Syamili.M',
    field_team: '',
    remarks: 'Two installments received; invoices and supporting documents not received yet.',
    installments: [
      {
        label: '1st Installment',
        amount: 503906,
        status: 'Received',
        milestone: 'Signing of MoU, Coordination with all schools',
        uc_date: '15.06.2026',
        uc_status: 'Not issued',
      },
      {
        label: '2nd Installment',
        amount: 755859,
        status: 'Received',
        milestone: 'Confirmation regarding readiness of dispatch of equipment',
        uc_date: '15.06.2026',
        uc_status: 'Not issued',
      },
      {
        label: '3rd Installment',
        amount: 1007812,
        status: 'Not Received',
        milestone: 'Delivery of all equipment, installation, completion of awareness sessions',
        uc_date: '20.07.2026',
        uc_status: 'Not issued',
      },
      {
        label: '4th Installment',
        amount: 251953,
        status: 'Not Received',
        milestone: 'Photographs of installed machines and submission of installation reports',
        uc_date: '30.08.2026',
        uc_status: 'Not issued',
      },
    ],
    phases: [
      { phase: 'Design & Initiation Phase', status: 'Completed', current: '', pending: '' },
      { phase: 'Implementation Phase', status: 'Ongoing', current: '', pending: '' },
      { phase: 'Monitoring & Evaluation Phase', status: 'Upcoming', current: '', pending: '' },
    ],
  },
  {
    id: 'sdp_03',
    sl_no: 3,
    project_number: '',
    name: 'Skill Advancement Program in Soilless Agriculture: Hydroponics and Aeroponics for Future Farming in Thiruvananthapuram',
    funding_agency: 'HLL',
    implementing_partner: 'HMA',
    location: 'Thiruvananthapuram',
    type: 'Other Public Health Project - CSR',
    status: 'Ongoing',
    components: 'Saffron Cultivation',
    duration: '8 months',
    start_date: '7-1-2026',
    end_date: '6-9-2026',
    beneficiaries_target: 100,
    beneficiaries_completed: 0,
    value: 2000000,
    expense_accounted: 91164,
    committed_expense: 0,
    fund_balance: 708836,
    project_officer: 'Shone Kiran K.S.',
    field_team: '',
    remarks: '',
    installments: [
      {
        label: '1st Installment',
        amount: 800000,
        status: 'Received',
        milestone: 'Amount used till 31 of March',
        uc_date: '31-03-2026',
        uc_status: 'Issued',
      },
      {
        label: '2nd Installment',
        amount: 1000000,
        status: 'Not Received',
        milestone: 'Upon Completion of 50% of work and submission of UC for 1st installment',
        uc_date: '06-07-2026',
        uc_status: 'Not Issued',
      },
      {
        label: '3rd Installment',
        amount: 200000,
        status: 'Not Received',
        milestone: 'Upon Completion of 100% of work and submission of 100% UC',
        uc_date: '21-08-2026',
        uc_status: 'Not Issued',
      },
    ],
    phases: [
      {
        phase: 'Design & Initiation Phase',
        status: 'Completed',
        current: 'Procurement',
        pending: 'Procurement of cold room, grow lights, racks, electrician, plumber',
      },
      {
        phase: 'Implementation Phase',
        status: 'Ongoing',
        current: '',
        pending: 'Construction Activities',
        pending_date: '07-07-2026',
        risk: 'Delay in confirmation and Procurement Process',
      },
      {
        phase: 'Monitoring & Evaluation Phase',
        status: 'Upcoming',
        current: '',
        pending: 'Submission of Final Report',
        pending_date: '09-09-2026',
      },
    ],
  },
  {
    id: 'sdp_04',
    sl_no: 4,
    project_number: '',
    name: 'TB Mukt Bharat Abhiyan - Nutrition Kit and Awareness Creation in Wayanad',
    funding_agency: 'HLL',
    implementing_partner: 'HMA',
    location: 'Wayanad',
    type: 'Other Public Health Project - CSR',
    status: 'Ongoing',
    components: 'Nutrition kit and Awareness creation',
    duration: '8 months',
    start_date: '7-1-2026',
    end_date: '6-9-2026',
    beneficiaries_target: 80,
    beneficiaries_completed: 0,
    value: 1000000,
    expense_accounted: 50000,
    committed_expense: 0,
    fund_balance: 950000,
    project_officer: 'Anjali A.S.',
    field_team: '',
    remarks: 'First Nutrition kit of May was given. The Second kit will be given shortly.',
    installments: [
      {
        label: 'Single Installment',
        amount: 1000000,
        status: 'Received',
        milestone: 'Amount used till 31 of March',
        uc_date: '31/3/2026',
        uc_status: 'Issued',
      },
    ],
    phases: [
      {
        phase: 'Design & Initiation Phase',
        status: 'Completed',
        current: 'Procurement process and IEC materials development',
        pending: '',
      },
      {
        phase: 'Implementation Phase',
        status: 'Ongoing',
        current: 'First Nutrition kit of May was given.',
        pending: '',
        risk: 'Heavy rain and flood risk',
      },
      { phase: 'Monitoring & Evaluation Phase', status: 'Upcoming', current: '', pending: '' },
    ],
  },
  {
    id: 'sdp_05',
    sl_no: 5,
    project_number: '',
    name: 'SERPL Bhubaneshwar - Millet Bar - POSHAN',
    funding_agency: 'IOCL SERPL Bhubaneshwar',
    implementing_partner: 'H&ND',
    location: 'Simdega, Jharkhand',
    type: 'Consultancy Project - CSR',
    status: 'Ongoing',
    components:
      'Distribution of 5,04,738 packs of millet bar to 6471 students in 41 Govt. schools for 6 months',
    duration: '6 months',
    start_date: '10.03.2026',
    end_date: '9.08.2026',
    beneficiaries_target: 6471,
    beneficiaries_completed: 0,
    value: 3494837,
    expense_accounted: 0,
    committed_expense: 0,
    fund_balance: 0,
    project_officer: 'Syamili.M',
    field_team: '',
    remarks: 'First installment received and first UC Submitted.',
    installments: [
      {
        label: '1st Installment',
        amount: 1048451,
        status: 'Received',
        milestone:
          'Signing of MoU, Coordination with schools, Confirmation of dispatch for 2 months',
        uc_date: '',
        uc_status: '',
      },
      {
        label: '2nd Installment',
        amount: 2096902,
        status: 'Not Received',
        milestone: 'Confirmation of delivery for 6 months from District Education Dept.',
        uc_date: '',
        uc_status: '',
      },
      {
        label: '3rd Installment',
        amount: 349484,
        status: 'Not Received',
        milestone: 'Upon successful distribution for 6 months and closure of project',
        uc_date: '',
        uc_status: '',
      },
    ],
    phases: [
      { phase: 'Design & Initiation Phase', status: 'Ongoing', current: '', pending: '' },
      { phase: 'Implementation Phase', status: 'Upcoming', current: '', pending: '' },
      { phase: 'Monitoring & Evaluation Phase', status: 'Upcoming', current: '', pending: '' },
    ],
  },
  {
    id: 'sdp_06',
    sl_no: 6,
    project_number: '',
    name: 'CPCL Nilgiris - Awareness Creation & Distribution of Menstrual Cups',
    funding_agency: 'CPCL',
    implementing_partner: 'HMA',
    location: 'Nilgiris district',
    type: 'M Cup Project - CSR',
    status: 'Ongoing',
    components: 'Menstrual Cup',
    duration: '1 year',
    start_date: '24/11/2025',
    end_date: '23/11/2026',
    beneficiaries_target: 6000,
    beneficiaries_completed: 1899,
    value: 2720000,
    expense_accounted: 1381563,
    committed_expense: 10000,
    fund_balance: -21563,
    project_officer: 'K Anakha Soman',
    field_team: 'Evangeline & Dr.Lenita',
    remarks: 'Weekly report submitted 20-06-2026.',
    installments: [
      {
        label: '1st Installment',
        amount: 1360000,
        status: 'Received',
        milestone: 'Upon Signing of MoU',
        uc_date: '30-05-2026',
        uc_status: 'Not Issued',
      },
      {
        label: '2nd Installment',
        amount: 816000,
        status: 'Not Received',
        milestone: 'Upon completion of 40% of work and submission of UC for 1st installment',
        uc_date: '30-08-2026',
        uc_status: 'Not Issued',
      },
      {
        label: '3rd Installment',
        amount: 544000,
        status: 'Not Received',
        milestone: 'Upon completion of 100% of work and submission of 100% UC',
        uc_date: '05-12-2026',
        uc_status: 'Not Issued',
      },
    ],
    phases: [
      {
        phase: 'Design & Initiation Phase',
        status: 'Completed',
        current: 'Designing, printing, M-Cup procurement, awareness schedule started',
        pending: '',
      },
      {
        phase: 'Implementation Phase',
        status: 'Ongoing',
        current: 'Awareness session ongoing',
        pending: 'Project Inauguration',
        pending_date: '18-06-2026',
      },
      {
        phase: 'Monitoring & Evaluation Phase',
        status: 'Upcoming',
        current: 'Documentation',
        pending: 'Project videography and submission of documents',
        pending_date: '10-10-2026',
      },
    ],
  },
  {
    id: 'sdp_07',
    sl_no: 7,
    project_number: '',
    name: 'HLL Beed-Thinkal - Awareness Creation & Distribution of Menstrual Cups among Sugarcane Workers in Maharashtra',
    funding_agency: 'HLL',
    implementing_partner: 'HMA',
    location: 'Maharashtra',
    type: 'M Cup Project - CSR',
    status: 'Ongoing',
    components: 'Menstrual Cup',
    duration: '1 year',
    start_date: '1-7-2026',
    end_date: '1-6-2027',
    beneficiaries_target: 2000,
    beneficiaries_completed: 798,
    value: 1000000,
    expense_accounted: 258419,
    committed_expense: 541625,
    fund_balance: 0,
    project_officer: 'Dr. Bhavya RJ',
    field_team: 'Aswini B Ranjane, Mahesh',
    remarks: '06/02/2026 interim report submitted.',
    installments: [
      {
        label: 'Single Installment (Rs.10,00,000)',
        amount: 1000000,
        status: 'Received',
        milestone: 'Upon Signing of MoU',
        uc_date: '09-10-2026',
        uc_status: 'Not issued',
      },
    ],
    phases: [
      {
        phase: 'Design & Initiation Phase',
        status: 'Completed',
        current: 'Need Assessment Completed',
        pending: '',
      },
      {
        phase: 'Implementation Phase',
        status: 'Ongoing',
        current: 'Awareness sessions ongoing',
        pending: 'Awareness session and distribution of MCup',
        pending_date: '30/08/2026',
        risk: 'Beneficiaries not willing; late schedule information',
      },
      {
        phase: 'Monitoring & Evaluation Phase',
        status: 'Upcoming',
        current: 'Documentation Activities',
        pending: '',
      },
    ],
  },
  {
    id: 'sdp_08',
    sl_no: 8,
    project_number: '',
    name: 'Aksharam - Smart Anganwadi for Bright Futures in Kerala',
    funding_agency: 'HLL',
    implementing_partner: 'HMA',
    location: 'Wayanad',
    type: 'Other Public Health Project - CSR',
    status: 'Ongoing',
    components: 'Smart Anganwadi',
    duration: '1 year',
    start_date: '07-01-2026',
    end_date: '06-01-2027',
    beneficiaries_target: 0,
    beneficiaries_completed: 0,
    value: 1000000,
    expense_accounted: 59432,
    committed_expense: 0,
    fund_balance: 940568,
    project_officer: 'Rejitha Ravi',
    field_team: '',
    remarks: 'Contract details shared with Procurement Facilitator.',
    installments: [
      {
        label: 'Single Installment (Rs.10,00,000)',
        amount: 1000000,
        status: 'Received',
        milestone: 'Amount used till 31 of March 2026',
        uc_date: '31/03/2026',
        uc_status: 'Issued',
      },
    ],
    phases: [
      {
        phase: 'Design & Initiation Phase',
        status: 'Ongoing',
        current: 'Quotation submission from external agencies awaited',
        pending: 'RFQ works in progress',
        pending_date: '23-6-2026',
        risk: 'climate challenges',
      },
      {
        phase: 'Implementation Phase',
        status: 'Upcoming',
        current: '',
        pending: 'Waiting for STEM institution to submit infrastructure specs.',
        pending_date: '20-6-2026',
      },
      { phase: 'Monitoring & Evaluation Phase', status: 'Upcoming', current: '', pending: '' },
    ],
  },
  {
    id: 'sdp_09',
    sl_no: 9,
    project_number: '',
    name: 'Navajeevana - Inclusive Community Mental Health Initiative in Wayanad District',
    funding_agency: 'HLL',
    implementing_partner: 'HMA',
    location: 'Wayanad',
    type: 'Other Public Health Project - CSR',
    status: 'Ongoing',
    components: 'Mental Health',
    duration: '2 year',
    start_date: '01-01-2025',
    end_date: '31/12/2026',
    beneficiaries_target: 50,
    beneficiaries_completed: 0,
    value: 3000000,
    expense_accounted: 334082,
    committed_expense: 211298,
    fund_balance: 654620,
    project_officer: 'Rejitha Ravi',
    field_team: '',
    remarks: '',
    installments: [
      {
        label: '1st Installment (Rs.12,00,000)',
        amount: 1200000,
        status: 'Received',
        milestone: 'Amount used till 31 of March 2026',
        uc_date: '31/03/2026',
        uc_status: 'Issued',
      },
      {
        label: '2nd Installment (Rs.15,00,000)',
        amount: 1500000,
        status: 'Not Received',
        milestone: 'Upon completion of 50% of work and submission of UC for 1st installment',
        uc_date: '3-11-2026',
        uc_status: 'Not Issued',
      },
      {
        label: '3rd Installment (Rs.3,00,000)',
        amount: 300000,
        status: 'Not Received',
        milestone: 'Upon completion of 100% of work and submission of UC',
        uc_date: '5-1-2027',
        uc_status: 'Not Issued',
      },
    ],
    phases: [
      {
        phase: 'Design & Initiation Phase',
        status: 'Ongoing',
        current: 'Empanelment - Work in Progress',
        pending: 'Empanelment Process',
        pending_date: '20-06-2025',
        risk: 'time limits',
      },
      { phase: 'Implementation Phase', status: 'Upcoming', current: '', pending: '' },
      { phase: 'Monitoring & Evaluation Phase', status: 'Upcoming', current: '', pending: '' },
    ],
  },
  {
    id: 'sdp_10',
    sl_no: 10,
    project_number: '',
    name: 'Terumo Penpol - Supply of IoT Bin',
    funding_agency: 'Terumo Penpol',
    implementing_partner: 'SPD',
    location: 'Trivandrum',
    type: 'Consultancy Project - CSR',
    status: 'Ongoing',
    components: 'IoT Bin - 2',
    duration: '4 Months',
    start_date: '25/03/2026',
    end_date: '',
    beneficiaries_target: 0,
    beneficiaries_completed: 0,
    value: 1260000,
    expense_accounted: 0,
    committed_expense: 0,
    fund_balance: 0,
    project_officer: 'Rakhi Mohan',
    field_team: '',
    remarks: 'Payment note initiated, UC not submitted yet.',
    installments: [
      {
        label: '1st Installment (Rs.12,60,000)',
        amount: 1260000,
        status: 'Received',
        milestone: 'Submission of fund request letter along with signing of MoU',
        uc_date: '25.07.2026',
        uc_status: 'Not Issued',
      },
    ],
    phases: [
      {
        phase: 'Monitoring & Evaluation Phase',
        status: 'Ongoing',
        current: '',
        pending: 'Hard copy of the signed MoU not received yet',
      },
    ],
  },
  {
    id: 'sdp_11',
    sl_no: 11,
    project_number: '',
    name: 'Govt Medical College, Konni - Supply of Biomedical Equipment',
    funding_agency: 'IOCL Kochi',
    implementing_partner: 'HCD',
    location: 'Konni, Pathanamthitta',
    type: 'Consultancy Project - CSR',
    status: 'Ongoing',
    components: 'Biomedical Equipment',
    duration: '4 Months',
    start_date: '',
    end_date: '',
    beneficiaries_target: 0,
    beneficiaries_completed: 0,
    value: 9450000,
    expense_accounted: 0,
    committed_expense: 0,
    fund_balance: 0,
    project_officer: 'Rakhi Mohan',
    field_team: '',
    remarks: 'Requested documents sent to funding agency.',
    installments: [
      {
        label: '1st Installment (25%) - Rs.23,62,500',
        amount: 2362500,
        status: 'Not Received',
        milestone: 'After signing of MOA, on issuance of PO to L-1 bidder',
        uc_date: '16/10/2026',
        uc_status: 'Not Issued',
      },
      {
        label: '2nd Installment (75%) - Rs.70,87,500',
        amount: 7087500,
        status: 'Not Received',
        milestone: 'On submission of UC of 1st installment, delivery and installation report',
        uc_date: '15/03/2027',
        uc_status: 'Not Issued',
      },
    ],
    phases: [
      { phase: 'Design & Initiation Phase', status: 'Ongoing', current: '', pending: '' },
      { phase: 'Implementation Phase', status: 'Upcoming', current: '', pending: '' },
      { phase: 'Monitoring & Evaluation Phase', status: 'Upcoming', current: '', pending: '' },
    ],
  },
  {
    id: 'sdp_12',
    sl_no: 12,
    project_number: 'CSR/IOCL/26-27/003/Healthcare',
    name: 'HLL-HCD P&S Consultancy Project - KSRTC Biomedical Equipment (Thiruvananthapuram)',
    funding_agency: 'IOCL Kochi',
    implementing_partner: 'HCD',
    location: 'KSRTC, East Fort, Thiruvananthapuram',
    type: 'Consultancy Project - CSR',
    status: 'Ongoing',
    components: 'Biomedical Equipment',
    duration: '4 Months',
    start_date: '',
    end_date: '',
    beneficiaries_target: 0,
    beneficiaries_completed: 0,
    value: 6500000,
    expense_accounted: 0,
    committed_expense: 0,
    fund_balance: 0,
    project_officer: '',
    field_team: '',
    remarks: 'The MoU has been forwarded for signing.',
    installments: [
      {
        label: '1st Installment (Rs.32,50,000)',
        amount: 3250000,
        status: 'Not Received',
        milestone: 'Submission of fund request with Proforma Invoice and PO records',
        uc_date: '',
        uc_status: '',
      },
      {
        label: '2nd Installment (Rs.26,00,000)',
        amount: 2600000,
        status: 'Not Received',
        milestone: 'Upon procurement of medical equipment and submission of UC for 1st installment',
        uc_date: '20.10.2026',
        uc_status: 'Not Issued',
      },
      {
        label: '3rd Installment (Rs.6,50,000)',
        amount: 650000,
        status: 'Not Received',
        milestone:
          'Supply and installation of all medical equipment, completion certificate, UC for 2nd installment',
        uc_date: '10-03-2027',
        uc_status: 'Not Issued',
      },
    ],
    phases: [
      { phase: 'Design & Initiation Phase', status: 'Ongoing', current: '', pending: '' },
      { phase: 'Implementation Phase', status: 'Upcoming', current: '', pending: '' },
      { phase: 'Monitoring & Evaluation Phase', status: 'Upcoming', current: '', pending: '' },
    ],
  },
  {
    id: 'sdp_13',
    sl_no: 13,
    project_number: '',
    name: 'KSBTC Van - Mobile Medical Unit for Thiruvananthapuram',
    funding_agency: 'IOCL Kochi',
    implementing_partner: 'HCD',
    location: 'Thiruvananthapuram',
    type: 'Consultancy Project - CSR',
    status: 'Ongoing',
    components: 'Biomedical Equipment',
    duration: '4 Months',
    start_date: '',
    end_date: '',
    beneficiaries_target: 0,
    beneficiaries_completed: 0,
    value: 4500000,
    expense_accounted: 0,
    committed_expense: 0,
    fund_balance: 0,
    project_officer: 'Swathy Krishna',
    field_team: '',
    remarks: 'MoU entering Sanction note Initiated.',
    installments: [
      {
        label: '1st Installment (Rs.36,00,000)',
        amount: 3600000,
        status: 'Not Received',
        milestone: 'Vehicle booking, Proforma invoice from Force Motors, Undertaking from KSBTC',
        uc_date: '10-11-2026',
        uc_status: 'Not Issued',
      },
      {
        label: '2nd Installment (Rs.9,00,000)',
        amount: 900000,
        status: 'Not Received',
        milestone: 'Vehicle delivery challan, Invoice, Registration certificate',
        uc_date: '16/03/2027',
        uc_status: 'Not Issued',
      },
    ],
    phases: [
      { phase: 'Design & Initiation Phase', status: 'Ongoing', current: '', pending: '' },
      { phase: 'Implementation Phase', status: 'Upcoming', current: '', pending: '' },
      { phase: 'Monitoring & Evaluation Phase', status: 'Upcoming', current: '', pending: '' },
    ],
  },
  {
    id: 'sdp_14',
    sl_no: 14,
    project_number: '',
    name: 'TB Nutrition Kit Project - YSR Kadapa District, Andhra Pradesh',
    funding_agency: 'HLL',
    implementing_partner: 'HMA',
    location: 'YSR Kadapa District, Andhra Pradesh',
    type: 'Other Public Health Project - CSR',
    status: 'Approved',
    components: 'Nutrition Kit',
    duration: '1 year',
    start_date: '',
    end_date: '',
    beneficiaries_target: 100,
    beneficiaries_completed: 0,
    value: 1272000,
    expense_accounted: 0,
    committed_expense: 0,
    fund_balance: 0,
    project_officer: 'Anjali A.S.',
    field_team: '',
    remarks: 'Awaiting MoU signing.',
    installments: [],
    phases: [],
  },
  {
    id: 'sdp_15',
    sl_no: 15,
    project_number: 'CSR/HLL/26-27/001/EDUCATION',
    name: 'Education Support Kit - Supply of Steel Water Bottles & Stationery to Govt Lower Primary School Students',
    funding_agency: 'HLL',
    implementing_partner: 'HMA',
    location: 'Thiruvananthapuram',
    type: 'Other Public Health Project - CSR',
    status: 'Approved',
    components: 'Supply of steel water bottles and pouches with stationery',
    duration: '',
    start_date: '',
    end_date: '',
    beneficiaries_target: 0,
    beneficiaries_completed: 0,
    value: 212625,
    expense_accounted: 0,
    committed_expense: 0,
    fund_balance: 0,
    project_officer: '',
    field_team: '',
    remarks: 'Awaiting MoU signing.',
    installments: [],
    phases: [],
  },
  {
    id: 'sdp_16',
    sl_no: 16,
    project_number: 'CSR/ALICO/26-27/002/Healthcare',
    name: 'HLL-HCS Consultancy Project - Comprehensive Healthcare Services in Kanpur & Faridabad (ALIMCO)',
    funding_agency: 'ALIMCO',
    implementing_partner: 'HCS',
    location: 'Kanpur, Uttar Pradesh & Faridabad, Haryana',
    type: 'Consultancy Project - CSR',
    status: 'Ongoing',
    components: 'Providing Comprehensive Healthcare Services - ALIMCO',
    duration: '6 Months',
    start_date: '22/05/2026',
    end_date: '21/11/2026',
    beneficiaries_target: 0,
    beneficiaries_completed: 0,
    value: 1456356,
    expense_accounted: 0,
    committed_expense: 0,
    fund_balance: 0,
    project_officer: 'Syamili.M',
    field_team: '',
    remarks: 'First Installment not received yet.',
    installments: [
      {
        label: '1st Installment (Rs.3,64,089)',
        amount: 364089,
        status: 'Not Received',
        milestone: 'Advance after signing of MoA on request for release of fund',
        uc_date: '30.07.2026',
        uc_status: '',
      },
      {
        label: '2nd Installment (Rs.7,28,178)',
        amount: 728178,
        status: 'Not Received',
        milestone:
          'After completion of project and submission of registration forms and medicine forms',
        uc_date: '',
        uc_status: '',
      },
      {
        label: '3rd Installment (Rs.3,64,089)',
        amount: 364089,
        status: 'Not Received',
        milestone:
          'On submission of project report, Impact Assessment report, and UC certified by CA',
        uc_date: '',
        uc_status: '',
      },
    ],
    phases: [
      { phase: 'Design & Initiation Phase', status: 'Completed', current: '', pending: '' },
      { phase: 'Implementation Phase', status: 'Ongoing', current: '', pending: '' },
      { phase: 'Monitoring & Evaluation Phase', status: 'Upcoming', current: '', pending: '' },
    ],
  },
  {
    id: 'sdp_17',
    sl_no: 17,
    project_number: '',
    name: 'IREDA - Providing Healthcare Facilities via E-Mobile Health Clinics in Bihar',
    funding_agency: 'IREDA',
    implementing_partner: 'HCS',
    location: 'Bihar',
    type: 'Consultancy Project - CSR',
    status: 'Ongoing',
    components: 'Providing healthcare facilities via deployment of e-Mobile Health Clinics',
    duration: '18 Months',
    start_date: '14/01/2025',
    end_date: '',
    beneficiaries_target: 0,
    beneficiaries_completed: 0,
    value: 3240000,
    expense_accounted: 0,
    committed_expense: 0,
    fund_balance: 0,
    project_officer: 'Syamili.M',
    field_team: '',
    remarks: '',
    installments: [
      {
        label: '1st Installment - Rs.1,00,000 Advance',
        amount: 100000,
        status: 'Received',
        milestone: 'On acceptance of terms & conditions',
        uc_date: '',
        uc_status: 'Not issued',
      },
      {
        label: '2nd Installment (40%) - Rs.12,56,000',
        amount: 1256000,
        status: 'Not Received',
        milestone: 'On signing of MOU, procurement of E-carts, delivery confirmation for 5 blocks',
        uc_date: '',
        uc_status: '',
      },
      {
        label: '3rd Installment (30%) - Rs.9,42,000',
        amount: 942000,
        status: 'Not Received',
        milestone: 'Procurement of E-carts for remaining 4 blocks, submission of UC',
        uc_date: '',
        uc_status: '',
      },
      {
        label: '4th Installment (30%) - Rs.9,42,000',
        amount: 942000,
        status: 'Not Received',
        milestone: 'Complete commissioning of all E-MHCs and submission of UC',
        uc_date: '',
        uc_status: '',
      },
    ],
    phases: [
      { phase: 'Design & Initiation Phase', status: 'Ongoing', current: '', pending: '' },
      { phase: 'Implementation Phase', status: 'Upcoming', current: '', pending: '' },
      { phase: 'Monitoring & Evaluation Phase', status: 'Upcoming', current: '', pending: '' },
    ],
  },
]

// ─────────────────────────────────────────────────────────────────────────────
// Derived filter lists (computed from actual CSV data)
// ─────────────────────────────────────────────────────────────────────────────

export const SDP_TYPES = [...new Set(SDP_PROJECTS.map((p) => p.type))].sort()
export const SDP_FUNDING_AGENCIES = [...new Set(SDP_PROJECTS.map((p) => p.funding_agency))].sort()
export const SDP_PARTNERS = [...new Set(SDP_PROJECTS.map((p) => p.implementing_partner))].sort()
export const SDP_STATUSES = ['Ongoing', 'Approved', 'Completed']
