import { ROLE } from './roles'
import { MODULE } from './modules'

export const ACCESS = {
  VIEW: 'V',
  EDIT: 'E',
  NONE: null,
}

export const PERMISSIONS = {
  // ── EMS ─────────────────────────────────────────────────────────────
  [MODULE.DASHBOARD]: {
    [ROLE.CEO]: ACCESS.VIEW,
    [ROLE.HEADS]: ACCESS.VIEW,
    [ROLE.HR]: ACCESS.VIEW,
    [ROLE.PROJECT_ASSOCIATE]: ACCESS.NONE,
    [ROLE.PROJECT_OFFICER]: ACCESS.NONE,
  },
  [MODULE.STAFF_PAYROLL]: {
    [ROLE.CEO]: ACCESS.VIEW,
    [ROLE.HEADS]: ACCESS.VIEW,
    [ROLE.HR]: ACCESS.EDIT,
    [ROLE.PROJECT_ASSOCIATE]: ACCESS.NONE,
    [ROLE.PROJECT_OFFICER]: ACCESS.NONE,
  },
  [MODULE.ATTENDANCE]: {
    [ROLE.CEO]: ACCESS.VIEW,
    [ROLE.HEADS]: ACCESS.VIEW,
    [ROLE.HR]: ACCESS.EDIT,
    [ROLE.PROJECT_ASSOCIATE]: ACCESS.NONE,
    [ROLE.PROJECT_OFFICER]: ACCESS.NONE,
  },
  [MODULE.EXPENSE_MANAGEMENT]: {
    [ROLE.CEO]: ACCESS.VIEW,
    [ROLE.HEADS]: ACCESS.VIEW,
    [ROLE.HR]: ACCESS.EDIT,
    [ROLE.PROJECT_ASSOCIATE]: ACCESS.NONE,
    [ROLE.PROJECT_OFFICER]: ACCESS.NONE,
  },
  [MODULE.REPORTS]: {
    [ROLE.CEO]: ACCESS.VIEW,
    [ROLE.HEADS]: ACCESS.VIEW,
    [ROLE.HR]: ACCESS.VIEW,
    [ROLE.PROJECT_ASSOCIATE]: ACCESS.NONE,
    [ROLE.PROJECT_OFFICER]: ACCESS.NONE,
  },
  [MODULE.AUDIT_LOGS]: {
    [ROLE.CEO]: ACCESS.VIEW,
    [ROLE.HEADS]: ACCESS.VIEW,
    [ROLE.HR]: ACCESS.VIEW,
    [ROLE.PROJECT_ASSOCIATE]: ACCESS.NONE,
    [ROLE.PROJECT_OFFICER]: ACCESS.NONE,
  },
  [MODULE.GENERAL_EXPENSES]: {
    [ROLE.CEO]: ACCESS.VIEW,
    [ROLE.HEADS]: ACCESS.VIEW,
    [ROLE.HR]: ACCESS.EDIT,
    [ROLE.PROJECT_ASSOCIATE]: ACCESS.NONE,
    [ROLE.PROJECT_OFFICER]: ACCESS.NONE,
  },

  [MODULE.HR_POOL]: {
    [ROLE.CEO]: ACCESS.VIEW,
    [ROLE.HEADS]: ACCESS.VIEW,
    [ROLE.HR]: ACCESS.EDIT,
    [ROLE.PROJECT_ASSOCIATE]: ACCESS.NONE,
    [ROLE.PROJECT_OFFICER]: ACCESS.NONE,
  },
  [MODULE.INTERNSHIP]: {
    [ROLE.CEO]: ACCESS.VIEW,
    [ROLE.HEADS]: ACCESS.VIEW,
    [ROLE.HR]: ACCESS.EDIT,
    [ROLE.PROJECT_ASSOCIATE]: ACCESS.NONE,
    [ROLE.PROJECT_OFFICER]: ACCESS.NONE,
  },
  [MODULE.RECRUITMENT]: {
    [ROLE.CEO]: ACCESS.VIEW,
    [ROLE.HEADS]: ACCESS.VIEW,
    [ROLE.HR]: ACCESS.EDIT,
    [ROLE.PROJECT_ASSOCIATE]: ACCESS.NONE,
    [ROLE.PROJECT_OFFICER]: ACCESS.NONE,
  },

  // Employee can only view their own profile — no access to any other EMS module
  [MODULE.MY_PROFILE]: {
    [ROLE.EMPLOYEE]: ACCESS.VIEW,
  },

  // Admin and HR can manage system users (register Google accounts + assign roles)
  [MODULE.USER_MANAGEMENT]: {
    [ROLE.ADMIN]: ACCESS.EDIT,
    [ROLE.HR]: ACCESS.EDIT,
    [ROLE.CEO]: ACCESS.VIEW,
  },

  // Admin-only settings page (Admin bypasses automatically; explicit NONE for all others)
  [MODULE.ADMIN_SETTINGS]: {
    [ROLE.CEO]: ACCESS.NONE,
    [ROLE.HEADS]: ACCESS.NONE,
    [ROLE.HR]: ACCESS.NONE,
    [ROLE.EMPLOYEE]: ACCESS.NONE,
    [ROLE.PROJECT_ASSOCIATE]: ACCESS.NONE,
    [ROLE.PROJECT_OFFICER]: ACCESS.NONE,
  },

  // CEO (and Admin via bypass) can compose, send, manage notes & sent history
  [MODULE.CEO_ANNOUNCEMENTS]: {
    [ROLE.CEO]: ACCESS.EDIT,
    [ROLE.HEADS]: ACCESS.NONE,
    [ROLE.HR]: ACCESS.NONE,
    [ROLE.EMPLOYEE]: ACCESS.NONE,
    [ROLE.PROJECT_ASSOCIATE]: ACCESS.NONE,
    [ROLE.PROJECT_OFFICER]: ACCESS.NONE,
  },

  // Every role except CEO receives announcements in their inbox
  [MODULE.NOTIFICATIONS]: {
    [ROLE.CEO]: ACCESS.NONE,
    [ROLE.HEADS]: ACCESS.VIEW,
    [ROLE.HR]: ACCESS.VIEW,
    [ROLE.EMPLOYEE]: ACCESS.VIEW,
    [ROLE.PROJECT_ASSOCIATE]: ACCESS.VIEW,
    [ROLE.PROJECT_OFFICER]: ACCESS.VIEW,
  },

  // ── PMS ─────────────────────────────────────────────────────────────
  [MODULE.PMS_DASHBOARD]: {
    [ROLE.CEO]: ACCESS.VIEW,
    [ROLE.HEADS]: ACCESS.VIEW,
    [ROLE.HR]: ACCESS.NONE,
    [ROLE.PROJECT_ASSOCIATE]: ACCESS.VIEW,
    [ROLE.PROJECT_OFFICER]: ACCESS.VIEW,
  },
  [MODULE.PMS_PROJECTS]: {
    [ROLE.CEO]: ACCESS.EDIT,
    [ROLE.HEADS]: ACCESS.EDIT,
    [ROLE.HR]: ACCESS.VIEW,
    [ROLE.PROJECT_ASSOCIATE]: ACCESS.EDIT,
    [ROLE.PROJECT_OFFICER]: ACCESS.VIEW,
  },
  [MODULE.PMS_LIFECYCLE]: {
    [ROLE.CEO]: ACCESS.EDIT,
    [ROLE.HEADS]: ACCESS.EDIT,
    [ROLE.HR]: ACCESS.NONE,
    [ROLE.PROJECT_ASSOCIATE]: ACCESS.EDIT,
    [ROLE.PROJECT_OFFICER]: ACCESS.VIEW,
  },
  [MODULE.PMS_EXPENSES]: {
    [ROLE.CEO]: ACCESS.VIEW,
    [ROLE.HEADS]: ACCESS.VIEW,
    [ROLE.HR]: ACCESS.NONE,
    [ROLE.PROJECT_ASSOCIATE]: ACCESS.EDIT,
    [ROLE.PROJECT_OFFICER]: ACCESS.EDIT,
  },
  [MODULE.PMS_DOCUMENTS]: {
    [ROLE.CEO]: ACCESS.VIEW,
    [ROLE.HEADS]: ACCESS.VIEW,
    [ROLE.HR]: ACCESS.NONE,
    [ROLE.PROJECT_ASSOCIATE]: ACCESS.EDIT,
    [ROLE.PROJECT_OFFICER]: ACCESS.EDIT,
  },
  [MODULE.PMS_TEAMS]: {
    [ROLE.CEO]: ACCESS.EDIT,
    [ROLE.HEADS]: ACCESS.EDIT,
    [ROLE.HR]: ACCESS.NONE,
    [ROLE.PROJECT_ASSOCIATE]: ACCESS.EDIT,
    [ROLE.PROJECT_OFFICER]: ACCESS.VIEW,
  },
  [MODULE.PMS_LOCATIONS]: {
    [ROLE.CEO]: ACCESS.EDIT,
    [ROLE.HEADS]: ACCESS.EDIT,
    [ROLE.HR]: ACCESS.NONE,
    [ROLE.PROJECT_ASSOCIATE]: ACCESS.EDIT,
    [ROLE.PROJECT_OFFICER]: ACCESS.VIEW,
  },
  [MODULE.PMS_REPORTS]: {
    [ROLE.CEO]: ACCESS.VIEW,
    [ROLE.HEADS]: ACCESS.VIEW,
    [ROLE.HR]: ACCESS.NONE,
    [ROLE.PROJECT_ASSOCIATE]: ACCESS.VIEW,
    [ROLE.PROJECT_OFFICER]: ACCESS.VIEW,
  },
  [MODULE.PMS_AGENCIES]: {
    [ROLE.CEO]: ACCESS.EDIT,
    [ROLE.HEADS]: ACCESS.EDIT,
    [ROLE.HR]: ACCESS.NONE,
    [ROLE.PROJECT_ASSOCIATE]: ACCESS.EDIT,
    [ROLE.PROJECT_OFFICER]: ACCESS.VIEW,
  },
  [MODULE.PMS_PARTNERS]: {
    [ROLE.CEO]: ACCESS.EDIT,
    [ROLE.HEADS]: ACCESS.EDIT,
    [ROLE.HR]: ACCESS.NONE,
    [ROLE.PROJECT_ASSOCIATE]: ACCESS.EDIT,
    [ROLE.PROJECT_OFFICER]: ACCESS.VIEW,
  },
  [MODULE.PMS_DAILY_REPORTS]: {
    [ROLE.CEO]: ACCESS.VIEW,
    [ROLE.HEADS]: ACCESS.VIEW,
    [ROLE.HR]: ACCESS.NONE,
    [ROLE.PROJECT_ASSOCIATE]: ACCESS.VIEW,
    [ROLE.PROJECT_OFFICER]: ACCESS.EDIT,
  },
  [MODULE.PMS_SETTLEMENTS]: {
    [ROLE.CEO]: ACCESS.VIEW,
    [ROLE.HEADS]: ACCESS.VIEW,
    [ROLE.HR]: ACCESS.EDIT,
    [ROLE.PROJECT_ASSOCIATE]: ACCESS.NONE,
    [ROLE.PROJECT_OFFICER]: ACCESS.NONE,
  },
}
