import { ROLE } from './roles'
import { MODULE } from './modules'

export const ACCESS = {
  VIEW: 'V',
  EDIT: 'E',
  NONE: null,
}

export const PERMISSIONS = {
  // ── EMS ─────────────────────────────────────────────────────────────
  [MODULE.DASHBOARD]: {
    [ROLE.CEO]: ACCESS.VIEW,
    [ROLE.HEADS]: ACCESS.VIEW,
    [ROLE.HR]: ACCESS.VIEW,
    [ROLE.FINANCE]: ACCESS.VIEW,
    [ROLE.PROJECT_OFFICER]: ACCESS.NONE,
  },
  [MODULE.STAFF_PAYROLL]: {
    [ROLE.CEO]: ACCESS.VIEW,
    [ROLE.HEADS]: ACCESS.VIEW,
    [ROLE.HR]: ACCESS.EDIT,
    [ROLE.FINANCE]: ACCESS.VIEW,
    [ROLE.PROJECT_OFFICER]: ACCESS.NONE,
  },
  [MODULE.ATTENDANCE]: {
    [ROLE.CEO]: ACCESS.VIEW,
    [ROLE.HEADS]: ACCESS.VIEW,
    [ROLE.HR]: ACCESS.EDIT,
    [ROLE.FINANCE]: ACCESS.VIEW,
    [ROLE.PROJECT_OFFICER]: ACCESS.NONE,
  },
  [MODULE.EXPENSE_MANAGEMENT]: {
    [ROLE.CEO]: ACCESS.VIEW,
    [ROLE.HEADS]: ACCESS.VIEW,
    [ROLE.HR]: ACCESS.EDIT,
    [ROLE.FINANCE]: ACCESS.VIEW,
    [ROLE.PROJECT_OFFICER]: ACCESS.NONE,
  },
  [MODULE.FINANCE]: {
    [ROLE.CEO]: ACCESS.VIEW,
    [ROLE.HEADS]: ACCESS.VIEW,
    [ROLE.HR]: ACCESS.VIEW,
    [ROLE.FINANCE]: ACCESS.EDIT,
    [ROLE.PROJECT_OFFICER]: ACCESS.NONE,
  },
  [MODULE.REPORTS]: {
    [ROLE.CEO]: ACCESS.VIEW,
    [ROLE.HEADS]: ACCESS.VIEW,
    [ROLE.HR]: ACCESS.VIEW,
    [ROLE.FINANCE]: ACCESS.VIEW,
    [ROLE.PROJECT_OFFICER]: ACCESS.NONE,
  },
  [MODULE.AUDIT_LOGS]: {
    [ROLE.CEO]: ACCESS.VIEW,
    [ROLE.HEADS]: ACCESS.VIEW,
    [ROLE.HR]: ACCESS.VIEW,
    [ROLE.FINANCE]: ACCESS.VIEW,
    [ROLE.PROJECT_OFFICER]: ACCESS.NONE,
  },

  // ── PMS ─────────────────────────────────────────────────────────────
  [MODULE.PMS_DASHBOARD]: {
    [ROLE.CEO]: ACCESS.VIEW,
    [ROLE.HEADS]: ACCESS.VIEW,
    [ROLE.HR]: ACCESS.NONE,
    [ROLE.FINANCE]: ACCESS.VIEW,
    [ROLE.PROJECT_OFFICER]: ACCESS.VIEW,
  },
  [MODULE.PMS_PROJECTS]: {
    [ROLE.CEO]: ACCESS.EDIT,
    [ROLE.HEADS]: ACCESS.EDIT,
    [ROLE.HR]: ACCESS.NONE,
    [ROLE.FINANCE]: ACCESS.VIEW,
    [ROLE.PROJECT_OFFICER]: ACCESS.VIEW,
  },
  [MODULE.PMS_LIFECYCLE]: {
    [ROLE.CEO]: ACCESS.EDIT,
    [ROLE.HEADS]: ACCESS.EDIT,
    [ROLE.HR]: ACCESS.NONE,
    [ROLE.FINANCE]: ACCESS.VIEW,
    [ROLE.PROJECT_OFFICER]: ACCESS.VIEW,
  },
  [MODULE.PMS_EXPENSES]: {
    [ROLE.CEO]: ACCESS.VIEW,
    [ROLE.HEADS]: ACCESS.VIEW,
    [ROLE.HR]: ACCESS.NONE,
    [ROLE.FINANCE]: ACCESS.EDIT,
    [ROLE.PROJECT_OFFICER]: ACCESS.EDIT,
  },
  [MODULE.PMS_DOCUMENTS]: {
    [ROLE.CEO]: ACCESS.VIEW,
    [ROLE.HEADS]: ACCESS.VIEW,
    [ROLE.HR]: ACCESS.NONE,
    [ROLE.FINANCE]: ACCESS.VIEW,
    [ROLE.PROJECT_OFFICER]: ACCESS.EDIT,
  },
  [MODULE.PMS_TEAMS]: {
    [ROLE.CEO]: ACCESS.EDIT,
    [ROLE.HEADS]: ACCESS.EDIT,
    [ROLE.HR]: ACCESS.NONE,
    [ROLE.FINANCE]: ACCESS.VIEW,
    [ROLE.PROJECT_OFFICER]: ACCESS.VIEW,
  },
  [MODULE.PMS_LOCATIONS]: {
    [ROLE.CEO]: ACCESS.EDIT,
    [ROLE.HEADS]: ACCESS.EDIT,
    [ROLE.HR]: ACCESS.NONE,
    [ROLE.FINANCE]: ACCESS.VIEW,
    [ROLE.PROJECT_OFFICER]: ACCESS.VIEW,
  },
  [MODULE.PMS_REPORTS]: {
    [ROLE.CEO]: ACCESS.VIEW,
    [ROLE.HEADS]: ACCESS.VIEW,
    [ROLE.HR]: ACCESS.NONE,
    [ROLE.FINANCE]: ACCESS.VIEW,
    [ROLE.PROJECT_OFFICER]: ACCESS.VIEW,
  },
  [MODULE.PMS_AGENCIES]: {
    [ROLE.CEO]: ACCESS.EDIT,
    [ROLE.HEADS]: ACCESS.EDIT,
    [ROLE.HR]: ACCESS.NONE,
    [ROLE.FINANCE]: ACCESS.VIEW,
    [ROLE.PROJECT_OFFICER]: ACCESS.VIEW,
  },
  [MODULE.PMS_PARTNERS]: {
    [ROLE.CEO]: ACCESS.EDIT,
    [ROLE.HEADS]: ACCESS.EDIT,
    [ROLE.HR]: ACCESS.NONE,
    [ROLE.FINANCE]: ACCESS.VIEW,
    [ROLE.PROJECT_OFFICER]: ACCESS.VIEW,
  },
}
